# Generated by Django 5.2.11 on 2026-02-14 18:41

import apps.core.fields
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventario', '0002_add_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cuit', models.CharField(help_text='Tax ID (11 digits, Modulo-11 validated)', max_length=11)),
                ('doc_tipo', models.PositiveSmallIntegerField(choices=[(80, 'CUIT'), (86, 'CUIL'), (87, 'CDI'), (89, 'Libreta de Enrolamiento'), (90, 'Libreta Cívica'), (91, 'CI Extranjera'), (92, 'En trámite'), (93, 'Acta de Nacimiento'), (95, 'CI Buenos Aires'), (96, 'DNI'), (94, 'Pasaporte'), (99, 'Doc. (Otro) / Sin identificar'), (0, 'CI Policía Federal')], default=80, help_text='Document type code (80=CUIT, 96=DNI, 99=CF)')),
                ('condicion_iva', models.PositiveSmallIntegerField(choices=[(1, 'IVA Responsable Inscripto'), (4, 'IVA Sujeto Exento'), (5, 'Consumidor Final'), (6, 'Responsable Monotributo'), (7, 'Sujeto No Categorizado'), (8, 'Proveedor del Exterior'), (9, 'Cliente del Exterior'), (10, 'IVA Liberado – Ley Nº 19.640'), (13, 'Monotributista Social')], help_text='IVA condition — determines invoice type (A/B/C)')),
                ('razon_social', models.CharField(help_text='Legal business name or full name', max_length=255)),
                ('domicilio', models.TextField(blank=True, default='', help_text='Fiscal address')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('telefono', models.CharField(blank=True, default='', max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'ventas_customer',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='SaleOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('CONFIRMED', 'Confirmado'), ('INVOICED', 'Facturado')], db_index=True, default='DRAFT', max_length=10)),
                ('subtotal', apps.core.fields.MoneyField(help_text='Sum of item subtotals (before tax)')),
                ('total_iva', apps.core.fields.MoneyField(help_text='Total IVA amount')),
                ('total_amount', apps.core.fields.MoneyField(help_text='Final total (subtotal + IVA)')),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('invoiced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(help_text='Branch where sale originates (determines stock source)', on_delete=django.db.models.deletion.PROTECT, related_name='sale_orders', to='core.branch')),
                ('confirmed_by', models.ForeignKey(blank=True, help_text='Set by SaleService.confirm_sale() from request.user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_sales', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Customer for this sale', on_delete=django.db.models.deletion.PROTECT, related_name='sale_orders', to='gravitea_ventas.customer')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_orders', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Pedido de Venta',
                'verbose_name_plural': 'Pedidos de Venta',
                'db_table': 'ventas_saleorder',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=4, help_text='Quantity sold (matches StockMovement precision)', max_digits=16)),
                ('unit_price', apps.core.fields.MoneyField(help_text='Price per unit at time of sale (snapshot)')),
                ('subtotal', apps.core.fields.MoneyField(help_text='quantity * unit_price (auto-calculated)')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('21.00'), help_text='IVA rate percentage (inherited from Product.tax_rate)', max_digits=5)),
                ('iva_amount', apps.core.fields.MoneyField(help_text='IVA amount: subtotal * (tax_rate / 100)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(help_text='Product being sold', on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='inventario.product')),
                ('sale_order', models.ForeignKey(help_text='Parent sale order', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gravitea_ventas.saleorder')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_order_items', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Línea de Pedido',
                'verbose_name_plural': 'Líneas de Pedido',
                'db_table': 'ventas_saleorderitem',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(condition=models.Q(('is_active', True)), fields=['tenant_id', 'is_active'], name='idx_customer_tenant_active'),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'cuit'), name='uq_customer_cuit_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='saleorder',
            index=models.Index(fields=['tenant_id', 'status'], name='idx_saleorder_tenant_status'),
        ),
        migrations.AddIndex(
            model_name='saleorder',
            index=models.Index(fields=['tenant_id', 'customer_id'], name='idx_saleorder_tenant_customer'),
        ),
        migrations.AddIndex(
            model_name='saleorder',
            index=models.Index(fields=['tenant_id', '-sale_date'], name='idx_saleorder_tenant_date'),
        ),
        migrations.AddConstraint(
            model_name='saleorderitem',
            constraint=models.UniqueConstraint(fields=('sale_order_id', 'product_id'), name='uq_sale_item_product_per_order'),
        ),
    ]
