# Generated by Django 5.2.11 on 2026-02-20 14:39

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_businesstemplate_tenantfielddefinition_and_more'),
        ('gravitea_ventas', '0002_add_rls_policies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='custom_data',
            field=models.JSONField(blank=True, default=dict, help_text='Tenant-defined custom fields. Validated against TenantFieldDefinition.'),
        ),
        migrations.AddField(
            model_name='saleorder',
            name='custom_data',
            field=models.JSONField(blank=True, default=dict, help_text='Tenant-defined custom fields. Validated against TenantFieldDefinition.'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=django.contrib.postgres.indexes.GinIndex(fields=['custom_data'], name='idx_customer_custom_data', opclasses=['jsonb_path_ops']),
        ),
        migrations.AddIndex(
            model_name='saleorder',
            index=django.contrib.postgres.indexes.GinIndex(fields=['custom_data'], name='idx_saleorder_custom_data', opclasses=['jsonb_path_ops']),
        ),
    ]
