# Generated by Django 5.0.14 on 2025-11-27 18:58

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique tenant identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Business name", max_length=255)),
                (
                    "tax_id",
                    models.CharField(
                        blank=True,
                        help_text="CUIT/RUT tax identification number",
                        max_length=20,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "fiscal_config_public",
                    models.JSONField(
                        blank=True,
                        help_text="Non-sensitive fiscal configuration (puntos de venta, IVA condition)",
                        null=True,
                    ),
                ),
                (
                    "fiscal_secrets_ref",
                    models.CharField(
                        blank=True,
                        help_text="Reference to Google Secret Manager for AFIP credentials",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("FREE", "Free"),
                            ("PRO", "Pro"),
                            ("ENTERPRISE", "Enterprise"),
                        ],
                        default="FREE",
                        help_text="Subscription tier",
                        max_length=20,
                    ),
                ),
                (
                    "valid_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Subscription expiration date (NULL for FREE tier)",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Active tenant flag (False = suspended)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Record creation timestamp"),
                ),
            ],
            options={
                "verbose_name": "Tenant",
                "verbose_name_plural": "Tenants",
                "db_table": "tenant",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique branch identifier",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Branch display name (e.g., 'Casa Central', 'Sucursal Norte')",
                        max_length=255,
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        help_text="Physical street address",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Contact phone number",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "coordinates",
                    models.JSONField(
                        blank=True,
                        help_text="Geographic coordinates: {'lat': float, 'lng': float}",
                        null=True,
                    ),
                ),
                (
                    "afip_pos_number",
                    models.IntegerField(
                        blank=True,
                        help_text="AFIP punto de venta number (1-99999)",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, help_text="Active branch flag"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Record creation timestamp"),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        help_text="Parent tenant",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branches",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Branch",
                "verbose_name_plural": "Branches",
                "db_table": "branch",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["tenant_id", "is_active"],
                        name="branch_tenant__9ca734_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="branch",
            constraint=models.UniqueConstraint(
                condition=models.Q(("afip_pos_number__isnull", False)),
                fields=("tenant_id", "afip_pos_number"),
                name="unique_afip_pos_per_tenant",
            ),
        ),
    ]
