# Generated by Django 5.2.11 on 2026-02-20 14:39

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_rls_policies'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(help_text='URL-safe identifier (e.g., ferreteria)', unique=True)),
                ('name', models.CharField(help_text='Human-readable template name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Template purpose description')),
                ('modules', models.JSONField(default=list, help_text='List of module names to enable. Example: ["inventario", "ventas"]')),
                ('field_definitions', models.JSONField(default=list, help_text='List of field definition dicts to create per TenantFieldDefinition schema')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Business Template',
                'verbose_name_plural': 'Business Templates',
                'db_table': 'business_template',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TenantFieldDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_key', models.CharField(help_text='Snake_case identifier (unique per tenant+entity_type)', max_length=50, validators=[django.core.validators.RegexValidator('^[a-z][a-z0-9_]{0,49}$', 'field_key must be snake_case, start with a letter, max 50 chars')])),
                ('label', models.CharField(help_text='Human-readable display name', max_length=100)),
                ('entity_type', models.CharField(choices=[('product', 'Product'), ('customer', 'Customer'), ('supplier', 'Supplier'), ('sale_order', 'Sale Order')], help_text='Which entity this field applies to', max_length=20)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('boolean', 'Boolean'), ('date', 'Date'), ('select', 'Select')], help_text='Data type for validation and rendering', max_length=10)),
                ('section', models.CharField(default='custom_fields', help_text='UI grouping label', max_length=100)),
                ('position', models.PositiveIntegerField(default=0, help_text='Sort order within section')),
                ('required', models.BooleanField(default=False, help_text='Whether the field is mandatory on create/update')),
                ('default_value', models.JSONField(blank=True, help_text='Default value (type matches field_type). Applied on create only when key absent.', null=True)),
                ('choices', models.JSONField(blank=True, help_text='List of allowed values for select type. Example: ["acero","aluminio"]', null=True)),
                ('active', models.BooleanField(default=True, help_text='Inactive fields are excluded from validation and API response')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_definitions', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Field Definition',
                'verbose_name_plural': 'Tenant Field Definitions',
                'db_table': 'tenant_field_definition',
                'ordering': ['section', 'position', 'field_key'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'entity_type', 'field_key'), name='unique_field_per_tenant_entity')],
            },
        ),
        migrations.CreateModel(
            name='TenantModuleConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module', models.CharField(choices=[('inventario', 'Inventario'), ('ventas', 'Ventas'), ('facturacion', 'Facturación'), ('sync', 'Sync')], help_text='Module identifier', max_length=20)),
                ('enabled', models.BooleanField(default=True, help_text='Whether the module is active for this tenant')),
                ('settings', models.JSONField(blank=True, default=dict, help_text='Module-specific settings (future extensibility)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_configs', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Module Config',
                'verbose_name_plural': 'Tenant Module Configs',
                'db_table': 'tenant_module_config',
                'ordering': ['module'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'module'), name='unique_module_per_tenant')],
            },
        ),
    ]
