# Generated by Django 5.2.11 on 2026-02-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_businesstemplate_tenantfielddefinition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantfielddefinition',
            name='entity_type',
            field=models.CharField(choices=[('product', 'Product'), ('customer', 'Customer'), ('supplier', 'Supplier'), ('sale_order', 'Sale Order'), ('purchase_order', 'Purchase Order')], help_text='Which entity this field applies to', max_length=20),
        ),
    ]
