# Generated by Django 5.0.14 on 2025-11-27 19:00

import uuid

import django.db.models.deletion
from django.db import migrations, models

import apps.core.fields


def create_enum_types(apps, schema_editor):
    """Create PostgreSQL ENUM types for sync app."""
    with schema_editor.connection.cursor() as cursor:
        # Create sync_status_enum (using DO block since IF NOT EXISTS not supported for TYPE)
        cursor.execute(
            """
            DO $$ BEGIN
                CREATE TYPE sync_status_enum AS ENUM (
                    'PENDING',
                    'IN_PROGRESS',
                    'COMPLETED',
                    'FAILED',
                    'CONFLICT'
                );
            EXCEPTION
                WHEN duplicate_object THEN null;
            END $$;
        """
        )

        # Create operation_type_enum
        cursor.execute(
            """
            DO $$ BEGIN
                CREATE TYPE operation_type_enum AS ENUM (
                    'CREATE',
                    'UPDATE',
                    'DELETE'
                );
            EXCEPTION
                WHEN duplicate_object THEN null;
            END $$;
        """
        )

        # Create operation_status_enum
        cursor.execute(
            """
            DO $$ BEGIN
                CREATE TYPE operation_status_enum AS ENUM (
                    'PENDING',
                    'PROCESSING',
                    'APPLIED',
                    'REJECTED',
                    'CONFLICT'
                );
            EXCEPTION
                WHEN duplicate_object THEN null;
            END $$;
        """
        )


def drop_enum_types(apps, schema_editor):
    """Drop PostgreSQL ENUM types for sync app."""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("DROP TYPE IF EXISTS operation_status_enum CASCADE;")
        cursor.execute("DROP TYPE IF EXISTS operation_type_enum CASCADE;")
        cursor.execute("DROP TYPE IF EXISTS sync_status_enum CASCADE;")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        # Create ENUM types first
        migrations.RunPython(
            create_enum_types,
            reverse_code=drop_enum_types,
        ),
        # Create SyncSession model
        migrations.CreateModel(
            name="SyncSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique identifier for the POS terminal",
                        max_length=100,
                    ),
                ),
                (
                    "last_sync_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of last successful sync",
                        null=True,
                    ),
                ),
                (
                    "sync_vector",
                    models.JSONField(
                        default=dict,
                        help_text="Vector clock for sync state tracking",
                    ),
                ),
                (
                    "status",
                    apps.core.fields.PostgresEnumField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CONFLICT", "Conflict Resolution Required"),
                        ],
                        db_index=True,
                        default="PENDING",
                        enum_type="sync_status_enum",
                        help_text="Current sync status (PostgreSQL ENUM)",
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error details if sync failed",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        help_text="Branch the POS terminal belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_sessions",
                        to="core.branch",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_sessions",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sync Session",
                "verbose_name_plural": "Sync Sessions",
                "db_table": "sync_session",
                "ordering": ["-updated_at"],
            },
        ),
        # Create PendingOperation model
        migrations.CreateModel(
            name="PendingOperation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Client-generated UUID for idempotency",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "operation_type",
                    apps.core.fields.PostgresEnumField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                        ],
                        enum_type="operation_type_enum",
                        help_text="Type of operation (PostgreSQL ENUM)",
                        max_length=10,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        db_index=True,
                        help_text="Type of entity (Sale, StockMovement, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "entity_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="UUID of the affected entity",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        help_text="Operation data as JSON",
                    ),
                ),
                (
                    "client_timestamp",
                    models.DateTimeField(
                        help_text="Timestamp from client device",
                    ),
                ),
                (
                    "server_timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Timestamp when received by server",
                    ),
                ),
                (
                    "status",
                    apps.core.fields.PostgresEnumField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("APPLIED", "Applied"),
                            ("REJECTED", "Rejected"),
                            ("CONFLICT", "Conflict"),
                        ],
                        db_index=True,
                        default="PENDING",
                        enum_type="operation_status_enum",
                        help_text="Processing status (PostgreSQL ENUM)",
                        max_length=20,
                    ),
                ),
                (
                    "conflict_data",
                    models.JSONField(
                        blank=True,
                        help_text="Conflict resolution data if applicable",
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error details if operation failed",
                        null=True,
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when operation was processed",
                        null=True,
                    ),
                ),
                (
                    "sync_session",
                    models.ForeignKey(
                        db_column="sync_session_id",
                        help_text="Associated sync session",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_operations",
                        to="sync.syncsession",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_operations",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pending Operation",
                "verbose_name_plural": "Pending Operations",
                "db_table": "pending_operation",
                "ordering": ["client_timestamp"],
            },
        ),
        # Add constraints and indexes
        migrations.AddConstraint(
            model_name="syncsession",
            constraint=models.UniqueConstraint(
                fields=["tenant_id", "device_id"],
                name="unique_device_per_tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="pendingoperation",
            index=models.Index(
                fields=["tenant_id", "status", "client_timestamp"],
                name="idx_pending_op_status",
            ),
        ),
        migrations.AddIndex(
            model_name="pendingoperation",
            index=models.Index(
                fields=["tenant_id", "entity_type", "entity_id"],
                name="idx_pending_op_entity",
            ),
        ),
    ]
