# Generated by Django 5.0.14 on 2025-12-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("sync", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="pendingoperation",
            index=models.Index(
                condition=models.Q(("status", "PENDING")),
                fields=["tenant_id", "status"],
                name="idx_pending_op_queue",
            ),
        ),
    ]
