# Generated by Django 5.0.14 on 2025-12-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sync", "0002_add_performance_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="pendingoperation",
            name="retry_count",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Number of retry attempts for failed operations"
            ),
        ),
    ]
