# Generated by Django 5.2.9 on 2025-12-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('sync', '0003_add_retry_count'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pendingoperation',
            name='idx_pending_op_queue',
        ),
        migrations.AddIndex(
            model_name='pendingoperation',
            index=models.Index(condition=models.Q(('status', 'PENDING')), fields=['tenant_id', 'status'], name='idx_pending_op_queue'),
        ),
    ]
