# Generated by Django 5.2.12 on 2026-03-19 20:54

import apps.core.encryption.fields
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_add_purchase_order_entity_type'),
        ('gravitea_acopio', '0003_storage_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProducerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producer_cuit_encrypted', apps.core.encryption.fields.EncryptedCharField(max_length=700, validators=[django.core.validators.RegexValidator('^\\d{2}-\\d{8}-\\d$', message='CUIT must be in format XX-XXXXXXXX-X')])),
                ('producer_cuit_hash', apps.core.encryption.fields.BlindIndexField(blank=True, editable=False, null=True)),
                ('grain_balance_kg', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=17)),
                ('ars_balance', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=17)),
                ('usd_balance', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=17)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producer_accounts', to='core.branch')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producer_accounts', to='gravitea_acopio.campanaconfig')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('grain_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producer_accounts', to='gravitea_acopio.graintype')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producer_accounts', to='core.tenant')),
            ],
            options={
                'db_table': 'cuentas_produceraccount',
            },
        ),
        migrations.CreateModel(
            name='AccountMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('CEG_DEPOSIT', 'Grain Deposit (CEG)'), ('LPG_SALE', 'Grain Sale (LPG)'), ('FIJACION', 'Price Fixation'), ('RETIRO', 'Cash Withdrawal'), ('SERVICE_CHARGE', 'Service Charge'), ('CANJE_GRAIN_DEBIT', 'Canje Grain Debit'), ('CANJE_INPUT_CREDIT', 'Canje Input Credit'), ('RETENTION_DEDUCTION', 'Tax Retention'), ('ADJUSTMENT', 'Adjustment (Supervisor)')], max_length=30)),
                ('quantity_kg', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=17)),
                ('ars_amount', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=17)),
                ('usd_amount', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=17)),
                ('reference_document', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('movement_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('romaneo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_movements', to='gravitea_acopio.romaneo')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_movements', to='core.tenant')),
                ('producer_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='gravitea_cuentas.produceraccount')),
            ],
            options={
                'db_table': 'cuentas_accountmovement',
                'ordering': ['-movement_at'],
            },
        ),
        migrations.AddIndex(
            model_name='produceraccount',
            index=models.Index(fields=['tenant', 'producer_cuit_hash'], name='cuentas_pro_tenant__92a3ff_idx'),
        ),
        migrations.AddIndex(
            model_name='produceraccount',
            index=models.Index(fields=['tenant', 'branch', 'campaign'], name='cuentas_pro_tenant__b8437b_idx'),
        ),
        migrations.AddConstraint(
            model_name='produceraccount',
            constraint=models.UniqueConstraint(fields=('tenant', 'producer_cuit_hash', 'branch', 'grain_type', 'campaign'), name='unique_producer_account_per_dimension'),
        ),
        migrations.AddConstraint(
            model_name='produceraccount',
            constraint=models.CheckConstraint(condition=models.Q(('grain_balance_kg__gte', 0)), name='grain_balance_kg_non_negative'),
        ),
        migrations.AddIndex(
            model_name='accountmovement',
            index=models.Index(fields=['producer_account', '-movement_at'], name='cuentas_acc_produce_d9800a_idx'),
        ),
        migrations.AddIndex(
            model_name='accountmovement',
            index=models.Index(fields=['tenant', 'movement_type'], name='cuentas_acc_tenant__70dca5_idx'),
        ),
    ]
