# Generated by Django 5.2 for Gravitea ERP
# Initial migration for facturacion (electronic invoicing) app

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models

import apps.core.encryption.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        # ============================================================
        # ARCACredential
        # ============================================================
        migrations.CreateModel(
            name="ARCACredential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "cuit_holder",
                    models.CharField(
                        help_text="Certificate holder CUIT (11 digits, no hyphens)",
                        max_length=11,
                    ),
                ),
                (
                    "cuit_represented",
                    models.CharField(
                        blank=True,
                        help_text="Represented company CUIT (delegation model)",
                        max_length=11,
                        null=True,
                    ),
                ),
                (
                    "certificate_pem",
                    models.TextField(
                        help_text="X.509 certificate in PEM format",
                    ),
                ),
                (
                    "private_key_pem",
                    apps.core.encryption.fields.EncryptedTextField(
                        help_text="RSA private key (AES-256-GCM encrypted at rest)",
                    ),
                ),
                (
                    "is_production",
                    models.BooleanField(
                        default=False,
                        help_text="True=production, False=homologacion",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Soft-disable without deletion",
                    ),
                ),
                (
                    "certificate_expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Certificate expiration (for system check warnings)",
                        null=True,
                    ),
                ),
                (
                    "last_unique_id",
                    models.BigIntegerField(
                        default=0,
                        help_text="Last TRA uniqueId for replay protection",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arca_credentials",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "ARCA Credential",
                "verbose_name_plural": "ARCA Credentials",
                "db_table": "facturacion_arcacredential",
            },
        ),
        migrations.AddConstraint(
            model_name="arcacredential",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "is_production"),
                name="uq_arca_credential_tenant_env",
            ),
        ),
        # ============================================================
        # PuntoDeVenta
        # ============================================================
        migrations.CreateModel(
            name="PuntoDeVenta",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "numero",
                    models.PositiveIntegerField(
                        help_text="Punto de venta number (1-99999)",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("electronic", "Electrónico"), ("manual", "Manual")],
                        default="electronic",
                        help_text="Emission type",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Human-readable label",
                        max_length=100,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Active flag",
                    ),
                ),
                (
                    "fecha_alta",
                    models.DateField(
                        blank=True,
                        help_text="ARCA registration date",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="puntos_de_venta",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Punto de Venta",
                "verbose_name_plural": "Puntos de Venta",
                "db_table": "facturacion_puntodeventa",
                "ordering": ["numero"],
            },
        ),
        migrations.AddConstraint(
            model_name="puntodeventa",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "numero"),
                name="uq_punto_venta_tenant",
            ),
        ),
        migrations.AddConstraint(
            model_name="puntodeventa",
            constraint=models.CheckConstraint(
                check=models.Q(numero__gte=1, numero__lte=99999),
                name="ck_punto_venta_range",
            ),
        ),
        # ============================================================
        # CAEA (must be before Comprobante since Comprobante FKs to it)
        # ============================================================
        migrations.CreateModel(
            name="CAEA",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "caea_code",
                    models.CharField(
                        help_text="14-digit CAEA from ARCA",
                        max_length=14,
                        unique=True,
                    ),
                ),
                (
                    "periodo",
                    models.CharField(
                        help_text="Period YYYYMM",
                        max_length=6,
                    ),
                ),
                (
                    "orden",
                    models.PositiveSmallIntegerField(
                        help_text="1=first quincena, 2=second",
                    ),
                ),
                (
                    "fch_vig_desde",
                    models.DateField(
                        help_text="Validity start date",
                    ),
                ),
                (
                    "fch_vig_hasta",
                    models.DateField(
                        help_text="Validity end date",
                    ),
                ),
                (
                    "fch_tope_inf",
                    models.DateField(
                        help_text="Reporting deadline",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Activo"),
                            ("REPORTED", "Informado"),
                            ("REPORTED_NO_MOVEMENT", "Sin movimiento informado"),
                            ("EXPIRED", "Vencido"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        help_text="CAEA lifecycle status",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="caeas",
                        to="core.tenant",
                    ),
                ),
                (
                    "punto_venta",
                    models.ForeignKey(
                        help_text="Associated punto de venta",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="caeas",
                        to="gravitea_facturacion.puntodeventa",
                    ),
                ),
            ],
            options={
                "verbose_name": "CAEA",
                "verbose_name_plural": "CAEAs",
                "db_table": "facturacion_caea",
                "ordering": ["-periodo", "-orden"],
            },
        ),
        migrations.AddConstraint(
            model_name="caea",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "punto_venta", "periodo", "orden"),
                name="uq_caea_period",
            ),
        ),
        # ============================================================
        # Comprobante
        # ============================================================
        migrations.CreateModel(
            name="Comprobante",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "cbte_tipo",
                    models.PositiveSmallIntegerField(
                        help_text="CbteTipo code (1,2,3,6,7,8,11,12,13,51,52,53)",
                    ),
                ),
                (
                    "cbte_nro",
                    models.PositiveBigIntegerField(
                        help_text="Sequential number per PtoVta+CbteTipo",
                    ),
                ),
                (
                    "concepto",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="1=Productos, 2=Servicios, 3=Ambos",
                    ),
                ),
                (
                    "doc_tipo",
                    models.PositiveSmallIntegerField(
                        help_text="Buyer document type (DocTipo code)",
                    ),
                ),
                (
                    "doc_nro",
                    models.CharField(
                        help_text="Buyer document number",
                        max_length=20,
                    ),
                ),
                (
                    "cbte_fch",
                    models.DateField(
                        help_text="Invoice date",
                    ),
                ),
                (
                    "fch_serv_desde",
                    models.DateField(
                        blank=True,
                        help_text="Service start date (Concepto 2,3)",
                        null=True,
                    ),
                ),
                (
                    "fch_serv_hasta",
                    models.DateField(
                        blank=True,
                        help_text="Service end date (Concepto 2,3)",
                        null=True,
                    ),
                ),
                (
                    "fch_vto_pago",
                    models.DateField(
                        blank=True,
                        help_text="Payment due date (Concepto 2,3)",
                        null=True,
                    ),
                ),
                (
                    "imp_total",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Total amount",
                        max_digits=17,
                    ),
                ),
                (
                    "imp_neto",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Net taxable amount",
                        max_digits=17,
                    ),
                ),
                (
                    "imp_iva",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.000"),
                        help_text="Total IVA",
                        max_digits=17,
                    ),
                ),
                (
                    "imp_trib",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.000"),
                        help_text="Other taxes total",
                        max_digits=17,
                    ),
                ),
                (
                    "imp_op_ex",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.000"),
                        help_text="IVA-exempt amount",
                        max_digits=17,
                    ),
                ),
                (
                    "imp_tot_conc",
                    models.DecimalField(
                        decimal_places=3,
                        default=Decimal("0.000"),
                        help_text="Non-taxable conceptual amount",
                        max_digits=17,
                    ),
                ),
                (
                    "mon_id",
                    models.CharField(
                        default="PES",
                        help_text="Currency code (PES=ARS)",
                        max_length=3,
                    ),
                ),
                (
                    "mon_cotiz",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("1.000000"),
                        help_text="Exchange rate",
                        max_digits=10,
                    ),
                ),
                (
                    "emitter_cuit",
                    models.CharField(
                        help_text="Emitter CUIT (11 digits)",
                        max_length=11,
                    ),
                ),
                (
                    "emitter_condicion_iva",
                    models.PositiveSmallIntegerField(
                        help_text="Emitter CondicionIVA code",
                    ),
                ),
                (
                    "receptor_condicion_iva",
                    models.PositiveSmallIntegerField(
                        help_text="Buyer CondicionIVA code",
                    ),
                ),
                (
                    "cae",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="14-digit CAE from ARCA",
                        max_length=14,
                        null=True,
                    ),
                ),
                (
                    "cae_fch_vto",
                    models.DateField(
                        blank=True,
                        help_text="CAE expiration date",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Borrador"),
                            ("VALIDANDO", "Validando con ARCA"),
                            ("AUTORIZADO", "Autorizado (CAE otorgado)"),
                            ("OBSERVADO", "Observado (CAE con advertencias)"),
                            ("RECHAZADO", "Rechazado por ARCA"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        help_text="Comprobante lifecycle status",
                        max_length=12,
                    ),
                ),
                (
                    "arca_response",
                    models.JSONField(
                        blank=True,
                        help_text="Full ARCA response snapshot",
                        null=True,
                    ),
                ),
                (
                    "arca_errors",
                    models.JSONField(
                        blank=True,
                        help_text="ARCA error/observation details",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="comprobantes",
                        to="core.tenant",
                    ),
                ),
                (
                    "punto_venta",
                    models.ForeignKey(
                        help_text="Associated punto de venta",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="comprobantes",
                        to="gravitea_facturacion.puntodeventa",
                    ),
                ),
                (
                    "caea",
                    models.ForeignKey(
                        blank=True,
                        help_text="CAEA reference (offline mode)",
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="comprobantes",
                        to="gravitea_facturacion.caea",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comprobante",
                "verbose_name_plural": "Comprobantes",
                "db_table": "facturacion_comprobante",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="comprobante",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "punto_venta", "cbte_tipo", "cbte_nro"),
                name="uq_comprobante_fiscal",
            ),
        ),
        migrations.AddIndex(
            model_name="comprobante",
            index=models.Index(
                fields=["tenant_id", "status"],
                name="idx_comprobante_tenant_status",
            ),
        ),
        migrations.AddIndex(
            model_name="comprobante",
            index=models.Index(
                fields=["tenant_id", "cbte_fch"],
                name="idx_comprobante_tenant_date",
            ),
        ),
        # ============================================================
        # AlicIva
        # ============================================================
        migrations.CreateModel(
            name="AlicIva",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "iva_id",
                    models.PositiveSmallIntegerField(
                        help_text="ARCA IVA code (3=0%, 4=10.5%, 5=21%, 6=27%, 8=5%, 9=2.5%)",
                    ),
                ),
                (
                    "base_imp",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Taxable base amount",
                        max_digits=17,
                    ),
                ),
                (
                    "importe",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="IVA amount",
                        max_digits=17,
                    ),
                ),
                (
                    "comprobante",
                    models.ForeignKey(
                        help_text="Parent comprobante",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="aliciva_set",
                        to="gravitea_facturacion.comprobante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alícuota IVA",
                "verbose_name_plural": "Alícuotas IVA",
                "db_table": "facturacion_aliciva",
            },
        ),
        # ============================================================
        # Tributo
        # ============================================================
        migrations.CreateModel(
            name="Tributo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tributo_id",
                    models.PositiveSmallIntegerField(
                        help_text="ARCA tribute type code",
                    ),
                ),
                (
                    "desc",
                    models.CharField(
                        help_text="Tax description",
                        max_length=100,
                    ),
                ),
                (
                    "base_imp",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Taxable base",
                        max_digits=17,
                    ),
                ),
                (
                    "alic",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Tax rate (%)",
                        max_digits=5,
                    ),
                ),
                (
                    "importe",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Tax amount",
                        max_digits=17,
                    ),
                ),
                (
                    "comprobante",
                    models.ForeignKey(
                        help_text="Parent comprobante",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="tributo_set",
                        to="gravitea_facturacion.comprobante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tributo",
                "verbose_name_plural": "Tributos",
                "db_table": "facturacion_tributo",
            },
        ),
        # ============================================================
        # CbteAsoc
        # ============================================================
        migrations.CreateModel(
            name="CbteAsoc",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo",
                    models.PositiveSmallIntegerField(
                        help_text="Associated CbteTipo code",
                    ),
                ),
                (
                    "pto_vta",
                    models.PositiveIntegerField(
                        help_text="Associated PtoVta number",
                    ),
                ),
                (
                    "nro",
                    models.PositiveBigIntegerField(
                        help_text="Associated CbteNro",
                    ),
                ),
                (
                    "cuit",
                    models.CharField(
                        blank=True,
                        help_text="Associated emitter CUIT (optional)",
                        max_length=11,
                        null=True,
                    ),
                ),
                (
                    "comprobante",
                    models.ForeignKey(
                        help_text="Parent NC/ND comprobante",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="cbteasoc_set",
                        to="gravitea_facturacion.comprobante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comprobante Asociado",
                "verbose_name_plural": "Comprobantes Asociados",
                "db_table": "facturacion_cbteasoc",
            },
        ),
        # ============================================================
        # RLS Policies (T010)
        # ============================================================
        migrations.RunSQL(
            sql=[
                # ARCACredential RLS
                "ALTER TABLE facturacion_arcacredential ENABLE ROW LEVEL SECURITY;",
                "ALTER TABLE facturacion_arcacredential FORCE ROW LEVEL SECURITY;",
                """
                CREATE POLICY arcacredential_tenant_isolation
                    ON facturacion_arcacredential
                    USING (tenant_id = current_setting('app.current_tenant_id')::uuid)
                    WITH CHECK (tenant_id = current_setting('app.current_tenant_id')::uuid);
                """,
                # PuntoDeVenta RLS
                "ALTER TABLE facturacion_puntodeventa ENABLE ROW LEVEL SECURITY;",
                "ALTER TABLE facturacion_puntodeventa FORCE ROW LEVEL SECURITY;",
                """
                CREATE POLICY puntodeventa_tenant_isolation
                    ON facturacion_puntodeventa
                    USING (tenant_id = current_setting('app.current_tenant_id')::uuid)
                    WITH CHECK (tenant_id = current_setting('app.current_tenant_id')::uuid);
                """,
                # Comprobante RLS
                "ALTER TABLE facturacion_comprobante ENABLE ROW LEVEL SECURITY;",
                "ALTER TABLE facturacion_comprobante FORCE ROW LEVEL SECURITY;",
                """
                CREATE POLICY comprobante_tenant_isolation
                    ON facturacion_comprobante
                    USING (tenant_id = current_setting('app.current_tenant_id')::uuid)
                    WITH CHECK (tenant_id = current_setting('app.current_tenant_id')::uuid);
                """,
                # CAEA RLS
                "ALTER TABLE facturacion_caea ENABLE ROW LEVEL SECURITY;",
                "ALTER TABLE facturacion_caea FORCE ROW LEVEL SECURITY;",
                """
                CREATE POLICY caea_tenant_isolation
                    ON facturacion_caea
                    USING (tenant_id = current_setting('app.current_tenant_id')::uuid)
                    WITH CHECK (tenant_id = current_setting('app.current_tenant_id')::uuid);
                """,
            ],
            reverse_sql=[
                # Reverse: drop policies and disable RLS
                "DROP POLICY IF EXISTS arcacredential_tenant_isolation ON facturacion_arcacredential;",
                "ALTER TABLE facturacion_arcacredential DISABLE ROW LEVEL SECURITY;",
                "DROP POLICY IF EXISTS puntodeventa_tenant_isolation ON facturacion_puntodeventa;",
                "ALTER TABLE facturacion_puntodeventa DISABLE ROW LEVEL SECURITY;",
                "DROP POLICY IF EXISTS comprobante_tenant_isolation ON facturacion_comprobante;",
                "ALTER TABLE facturacion_comprobante DISABLE ROW LEVEL SECURITY;",
                "DROP POLICY IF EXISTS caea_tenant_isolation ON facturacion_caea;",
                "ALTER TABLE facturacion_caea DISABLE ROW LEVEL SECURITY;",
            ],
        ),
    ]
