# Generated by Django 5.2.12 on 2026-03-19 03:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_add_purchase_order_entity_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrainType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=5, unique=True)),
                ('arca_codigo', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('humedad_base_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hf_secado_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('manipuleo_fijo_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('volatil_fijo_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grading_system', models.CharField(choices=[('GRADO', 'Grado'), ('TOLERANCE', 'Tolerance')], default='GRADO', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'acopio_graintype',
                'ordering': ['code'],
                'constraints': [models.UniqueConstraint(fields=('code',), name='uq_graintype_code'), models.UniqueConstraint(fields=('arca_codigo',), name='uq_graintype_arca_codigo')],
            },
        ),
        migrations.CreateModel(
            name='CampanaConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('campaign_code', models.CharField(max_length=7)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campaign_configs', to='core.tenant')),
            ],
            options={
                'db_table': 'acopio_campanaconfig',
                'ordering': ['-start_date'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'campaign_code'), name='uq_campana_tenant_code'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('tenant', 'is_active'), name='uq_campana_one_active_per_tenant')],
            },
        ),
        migrations.CreateModel(
            name='MermaTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('materias_extranas_from_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('materias_extranas_to_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('zarandeo_deduction_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grain_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merma_bands', to='gravitea_acopio.graintype')),
            ],
            options={
                'db_table': 'acopio_mermatable',
                'indexes': [models.Index(fields=['grain_type', 'valid_to'], name='idx_merma_grain_valid'), models.Index(fields=['grain_type', 'materias_extranas_from_pct', 'valid_to'], name='idx_merma_grain_me_valid')],
            },
        ),
        migrations.CreateModel(
            name='ToleranceTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('parameter', models.CharField(max_length=50)),
                ('tolerance_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grado_base', models.IntegerField()),
                ('source_resolution', models.CharField(blank=True, max_length=100, null=True)),
                ('grain_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tolerance_entries', to='gravitea_acopio.graintype')),
            ],
            options={
                'db_table': 'acopio_tolerancetable',
                'indexes': [models.Index(fields=['grain_type', 'valid_to'], name='idx_tolerance_grain_valid'), models.Index(fields=['grain_type', 'parameter', 'grado_base', 'valid_to'], name='idx_tol_grain_param_grade')],
            },
        ),
    ]
