# Generated by Django 5.2.12 on 2026-03-19 13:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_purchase_order_entity_type'),
        ('gravitea_acopio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Romaneo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('romaneo_number', models.CharField(help_text='Auto-generated ROM-YYYY-NNNNN per branch.', max_length=20)),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('PESADO', 'Pesado'), ('ANALIZADO', 'Analizado'), ('CONFORME', 'Conforme'), ('CERRADO', 'Cerrado')], default='PENDIENTE', max_length=15)),
                ('ts_entrada', models.DateTimeField(auto_now_add=True)),
                ('ts_pesada_bruta', models.DateTimeField(blank=True, null=True)),
                ('ts_calado', models.DateTimeField(blank=True, help_text='Sampling timestamp.', null=True)),
                ('ts_analisis', models.DateTimeField(blank=True, null=True)),
                ('ts_descarga', models.DateTimeField(blank=True, null=True)),
                ('ts_tara', models.DateTimeField(blank=True, null=True)),
                ('patente_chasis', models.CharField(max_length=15)),
                ('patente_acoplado', models.CharField(blank=True, max_length=15, null=True)),
                ('driver_name', models.CharField(max_length=200)),
                ('driver_dni', models.CharField(max_length=20)),
                ('peso_bruto_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=17, null=True)),
                ('tara_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=17, null=True)),
                ('peso_neto_bruto_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=17, null=True)),
                ('weighbridge_device', models.CharField(blank=True, help_text='Placeholder for weighbridge integration.', max_length=100, null=True)),
                ('cpe_numero', models.CharField(max_length=20)),
                ('ctg_codigo', models.CharField(blank=True, max_length=20, null=True)),
                ('producer_cuit', models.CharField(max_length=13)),
                ('origin_locality', models.CharField(max_length=200)),
                ('device_id', models.CharField(blank=True, max_length=100, null=True)),
                ('grado_asignado', models.IntegerField(blank=True, null=True)),
                ('bonificacion_rebaja_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('peso_neto_conforme_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=17, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='romaneos', to='core.branch')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='romaneos', to='gravitea_acopio.campanaconfig')),
                ('grain_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='romaneos', to='gravitea_acopio.graintype')),
                ('laboratorista_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='romaneos_analyzed', to=settings.AUTH_USER_MODEL)),
                ('operator_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='romaneos_operated', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='romaneos', to='core.tenant')),
                ('tolerance_table_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='romaneos_graded', to='gravitea_acopio.tolerancetable')),
            ],
            options={
                'db_table': 'acopio_romaneo',
                'ordering': ['-ts_entrada'],
            },
        ),
        migrations.CreateModel(
            name='QualityAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('humedad_pct', models.DecimalField(decimal_places=2, help_text='Moisture % (Hi for secado formula).', max_digits=5)),
                ('materias_extranas_pct', models.DecimalField(decimal_places=2, help_text='Foreign matter %.', max_digits=5)),
                ('granos_danados_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('granos_quebrados_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('granos_ardidos_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cuerpos_extranos_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('peso_hectolitrico_kg', models.DecimalField(blank=True, decimal_places=2, help_text='Hectoliter weight (cereals only).', max_digits=5, null=True)),
                ('proteina_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Protein % (trigo only).', max_digits=5, null=True)),
                ('granos_verdes_pct', models.DecimalField(blank=True, decimal_places=2, help_text='Green grains % (soja only).', max_digits=5, null=True)),
                ('analysis_timestamp', models.DateTimeField()),
                ('sample_reference', models.CharField(blank=True, max_length=50, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_analyses', to='core.tenant')),
                ('romaneo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quality_analysis', to='gravitea_acopio.romaneo')),
            ],
            options={
                'db_table': 'acopio_qualityanalysis',
            },
        ),
        migrations.CreateModel(
            name='MermaCalculation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('peso_neto_bruto_input_kg', models.DecimalField(decimal_places=3, max_digits=17)),
                ('hi_input_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hf_used_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('materias_extranas_input_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('zarandeo_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('secado_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('manipuleo_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('volatil_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('peso_post_zarandeo_kg', models.DecimalField(decimal_places=3, max_digits=17)),
                ('peso_post_secado_kg', models.DecimalField(decimal_places=3, max_digits=17)),
                ('peso_post_manipuleo_kg', models.DecimalField(decimal_places=3, max_digits=17)),
                ('peso_final_kg', models.DecimalField(decimal_places=3, max_digits=17)),
                ('total_merma_kg', models.DecimalField(decimal_places=3, max_digits=17)),
                ('total_factor_pct', models.DecimalField(decimal_places=4, max_digits=7)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('calculated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merma_calculations', to=settings.AUTH_USER_MODEL)),
                ('merma_table_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calculations', to='gravitea_acopio.mermatable')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='merma_calculations', to='core.tenant')),
                ('romaneo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merma_calculation', to='gravitea_acopio.romaneo')),
            ],
            options={
                'db_table': 'acopio_mermacalculation',
            },
        ),
        migrations.AddIndex(
            model_name='romaneo',
            index=models.Index(fields=['tenant_id', 'status', 'ts_entrada'], name='idx_romaneo_tenant_status_ts'),
        ),
        migrations.AddIndex(
            model_name='romaneo',
            index=models.Index(fields=['tenant_id', 'branch_id', 'ts_entrada'], name='idx_romaneo_tenant_branch_ts'),
        ),
        migrations.AddIndex(
            model_name='romaneo',
            index=models.Index(fields=['tenant_id', 'campaign_id', 'grain_type_id'], name='idx_romaneo_tenant_camp_grain'),
        ),
        migrations.AddConstraint(
            model_name='romaneo',
            constraint=models.UniqueConstraint(fields=('tenant', 'cpe_numero'), name='uq_romaneo_tenant_cpe'),
        ),
        migrations.AddConstraint(
            model_name='romaneo',
            constraint=models.UniqueConstraint(fields=('tenant', 'romaneo_number'), name='uq_romaneo_tenant_number'),
        ),
    ]
