# Generated by Django 5.2.12 on 2026-03-19 17:36

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_purchase_order_entity_type'),
        ('gravitea_acopio', '0002_romaneo_core'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrainLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lot_code', models.CharField(help_text='Auto-generated: BRANCH-GRAIN-CAMPAIGN-GRADE.', max_length=100)),
                ('grado', models.IntegerField(help_text='1/2/3 for cereals; 0 for oleaginosas.')),
                ('total_kg', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=17)),
                ('is_own_grain', models.BooleanField(default=False, help_text='ADR-020: True→1.3.XX (own); False→8.1.XX (third-party custody).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grain_lots', to='core.branch')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grain_lots', to='gravitea_acopio.campanaconfig')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grain_lots_created', to=settings.AUTH_USER_MODEL)),
                ('grain_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grain_lots', to='gravitea_acopio.graintype')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grain_lots', to='core.tenant')),
            ],
            options={
                'db_table': 'acopio_grainlot',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='romaneo',
            name='grain_lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='romaneos', to='gravitea_acopio.grainlot'),
        ),
        migrations.CreateModel(
            name='StorageUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('unit_type', models.CharField(choices=[('SILO_VERTICAL', 'Silo Vertical'), ('CELDA_HORIZONTAL', 'Celda Horizontal'), ('SECADERO_BIN', 'Secadero / Bin')], max_length=20)),
                ('capacity_tonnes', models.DecimalField(decimal_places=3, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('environment_sensor_id', models.CharField(blank=True, help_text='IoT sensor anchor (Phase 4).', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='storage_units', to='core.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='storage_units_created', to=settings.AUTH_USER_MODEL)),
                ('current_grain_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_units', to='gravitea_acopio.graintype')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='storage_units', to='core.tenant')),
            ],
            options={
                'db_table': 'acopio_storageunit',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='grainlot',
            name='storage_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grain_lots', to='gravitea_acopio.storageunit'),
        ),
        migrations.AddField(
            model_name='romaneo',
            name='storage_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='romaneos', to='gravitea_acopio.storageunit'),
        ),
        migrations.CreateModel(
            name='GrainMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('DEPOSIT', 'Depósito'), ('WITHDRAWAL', 'Egreso'), ('TRANSFER_IN', 'Transferencia Entrada'), ('TRANSFER_OUT', 'Transferencia Salida'), ('ADJUSTMENT', 'Ajuste')], max_length=15)),
                ('quantity_kg', models.DecimalField(decimal_places=3, help_text='Positive=inflow; negative=outflow.', max_digits=17)),
                ('reference_document', models.CharField(blank=True, help_text='External doc ref for non-romaneo movements.', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('movement_at', models.DateTimeField(auto_now_add=True)),
                ('device_id', models.CharField(blank=True, help_text='Device provenance (ADR-034).', max_length=100, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grain_movements_created', to=settings.AUTH_USER_MODEL)),
                ('grain_lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='gravitea_acopio.grainlot')),
                ('romaneo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grain_movements', to='gravitea_acopio.romaneo')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grain_movements', to='core.tenant')),
            ],
            options={
                'db_table': 'acopio_grainmovement',
                'ordering': ['-movement_at'],
                'indexes': [models.Index(fields=['tenant_id', 'grain_lot_id', 'movement_at'], name='idx_gm_tenant_lot_ts'), models.Index(fields=['tenant_id', 'movement_type', 'movement_at'], name='idx_gm_tenant_type_ts')],
            },
        ),
        migrations.AddIndex(
            model_name='storageunit',
            index=models.Index(fields=['tenant_id', 'branch_id', 'is_active'], name='idx_su_tenant_branch_active'),
        ),
        migrations.AddConstraint(
            model_name='storageunit',
            constraint=models.UniqueConstraint(fields=('tenant', 'branch', 'name'), name='uq_storageunit_tenant_branch_name'),
        ),
        migrations.AddIndex(
            model_name='grainlot',
            index=models.Index(fields=['tenant_id', 'storage_unit_id'], name='idx_gl_tenant_storage'),
        ),
        migrations.AddIndex(
            model_name='grainlot',
            index=models.Index(fields=['tenant_id', 'campaign_id', 'grain_type_id'], name='idx_gl_tenant_camp_grain'),
        ),
        migrations.AddConstraint(
            model_name='grainlot',
            constraint=models.UniqueConstraint(fields=('tenant', 'branch', 'grain_type', 'campaign', 'grado', 'storage_unit'), name='uq_grainlot_composite_identity'),
        ),
        migrations.AddConstraint(
            model_name='grainlot',
            constraint=models.CheckConstraint(condition=models.Q(('total_kg__gte', 0)), name='chk_grainlot_nonnegative_balance'),
        ),
    ]
