# Generated by Django for Gravitea ERP
# Migration for inventario app

import uuid
from decimal import Decimal

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.core.encryption.fields
import apps.core.fields


def create_stock_movement_enum(apps, schema_editor):
    """
    Create stock_movement_type_enum if it doesn't exist.

    The ENUM should already exist from SQL schema (001_schema.sql),
    but we create it here for safety and test environments.
    """
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(
            """
            DO $$ BEGIN
                CREATE TYPE stock_movement_type_enum AS ENUM (
                    'SALE', 'PURCHASE', 'ADJ', 'TRANS_IN', 'TRANS_OUT'
                );
            EXCEPTION
                WHEN duplicate_object THEN null;
            END $$;
        """
        )


def drop_stock_movement_enum(apps, schema_editor):
    """Drop stock_movement_type_enum if reverting migration."""
    if schema_editor.connection.vendor == "postgresql":
        # Only drop if no tables are using it
        schema_editor.execute("DROP TYPE IF EXISTS stock_movement_type_enum CASCADE")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Ensure ENUM exists (may already exist from SQL schema)
        migrations.RunPython(create_stock_movement_enum, drop_stock_movement_enum),
        # 1. ProductCategory (depends on: tenant)
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(help_text="Category name", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_categories",
                        to="core.tenant",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent category (null for root categories)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="inventario.productcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Category",
                "verbose_name_plural": "Product Categories",
                "db_table": "product_category",
                "ordering": ["name"],
            },
        ),
        # 2. Supplier (depends on: tenant)
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(help_text="Supplier name", max_length=255)),
                (
                    "tax_id_encrypted",
                    apps.core.encryption.fields.EncryptedCharField(
                        blank=True,
                        help_text="Encrypted tax identification number",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "tax_id_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Blind index for tax_id searches",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "contact_info_encrypted",
                    apps.core.encryption.fields.EncryptedTextField(
                        blank=True, help_text="Encrypted contact information", null=True
                    ),
                ),
                (
                    "email_encrypted",
                    apps.core.encryption.fields.EncryptedCharField(
                        blank=True, help_text="Encrypted email address", max_length=355, null=True
                    ),
                ),
                (
                    "email_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Blind index for email searches",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "address_encrypted",
                    apps.core.encryption.fields.EncryptedTextField(
                        blank=True, help_text="Encrypted physical address", null=True
                    ),
                ),
                (
                    "lead_time_days",
                    models.IntegerField(
                        blank=True, help_text="Expected delivery lead time in days", null=True
                    ),
                ),
                (
                    "current_balance",
                    apps.core.fields.MoneyField(
                        decimal_places=3,
                        default=Decimal("0.000"),
                        help_text="Current account balance (payables)",
                        max_digits=17,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, help_text="Active/available flag"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suppliers",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier",
                "verbose_name_plural": "Suppliers",
                "db_table": "supplier",
                "ordering": ["name"],
            },
        ),
        # 3. PriceList (depends on: tenant)
        migrations.CreateModel(
            name="PriceList",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(help_text="Price list name", max_length=100)),
                (
                    "margin_pct",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Default margin percentage",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        db_index=True, default=False, help_text="Default price list flag"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_lists",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Price List",
                "verbose_name_plural": "Price Lists",
                "db_table": "price_list",
                "ordering": ["name"],
            },
        ),
        # 4. Product (depends on: tenant, product_category, supplier)
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        db_index=True,
                        help_text="Stock Keeping Unit (unique per tenant)",
                        max_length=50,
                    ),
                ),
                (
                    "barcode",
                    apps.core.encryption.fields.EncryptedCharField(
                        blank=True,
                        help_text="Product barcode (encrypted)",
                        max_length=355,
                        null=True,
                    ),
                ),
                (
                    "barcode_blind_idx",
                    apps.core.encryption.fields.BlindIndexField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        help_text="Blind index for barcode searches",
                        max_length=64,
                        null=True,
                    ),
                ),
                ("name", models.CharField(help_text="Product display name", max_length=255)),
                (
                    "description",
                    models.TextField(blank=True, help_text="Product description", null=True),
                ),
                (
                    "unit_price",
                    apps.core.fields.MoneyField(
                        decimal_places=3,
                        default=Decimal("0.000"),
                        help_text="Default selling price",
                        max_digits=17,
                    ),
                ),
                (
                    "cost_price",
                    apps.core.fields.MoneyField(
                        decimal_places=3,
                        default=Decimal("0.000"),
                        help_text="Last known cost price",
                        max_digits=17,
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("21.00"),
                        help_text="VAT rate percentage (default 21% for Argentina)",
                        max_digits=5,
                    ),
                ),
                (
                    "min_stock",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Minimum stock level for reorder alerts",
                        max_digits=16,
                        null=True,
                    ),
                ),
                (
                    "max_stock",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Maximum stock level",
                        max_digits=16,
                        null=True,
                    ),
                ),
                (
                    "attributes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Custom product attributes (JSON)",
                        null=True,
                    ),
                ),
                (
                    "ml_tags",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="ML-generated categorization tags (JSON)",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True, default=True, help_text="Active/available for sale"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="core.tenant",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        help_text="Product category",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="inventario.productcategory",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        help_text="Default supplier",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="inventario.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
                "db_table": "product",
                "ordering": ["name"],
            },
        ),
        # 5. ProductPriceHistory (depends on: product, price_list, app_user)
        migrations.CreateModel(
            name="ProductPriceHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "price",
                    apps.core.fields.MoneyField(
                        decimal_places=3,
                        default=Decimal("0.000"),
                        help_text="Price value",
                        max_digits=17,
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(db_index=True, help_text="Start of validity period"),
                ),
                (
                    "valid_to",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="End of validity period (null for current price)",
                        null=True,
                    ),
                ),
                (
                    "change_reason",
                    models.CharField(
                        blank=True, help_text="Reason for price change", max_length=255, null=True
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Product",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="inventario.product",
                    ),
                ),
                (
                    "price_list",
                    models.ForeignKey(
                        help_text="Price list",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="inventario.pricelist",
                    ),
                ),
                (
                    "changed_by_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who made the change",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="price_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Price History",
                "verbose_name_plural": "Product Price History",
                "db_table": "product_price_history",
                "ordering": ["-valid_from"],
            },
        ),
        # 6. ProductCostHistory (depends on: product)
        migrations.CreateModel(
            name="ProductCostHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "cost",
                    apps.core.fields.MoneyField(
                        decimal_places=3,
                        default=Decimal("0.000"),
                        help_text="Cost value",
                        max_digits=17,
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(db_index=True, help_text="Start of validity period"),
                ),
                (
                    "valid_to",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="End of validity period (null for current cost)",
                        null=True,
                    ),
                ),
                (
                    "source_doc",
                    models.CharField(
                        blank=True,
                        help_text="Source document reference (PO, invoice, etc.)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Product",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_history",
                        to="inventario.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Cost History",
                "verbose_name_plural": "Product Cost History",
                "db_table": "product_cost_history",
                "ordering": ["-valid_from"],
            },
        ),
        # 7. StockMovement (depends on: tenant, product, branch)
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "type",
                    apps.core.fields.PostgresEnumField(
                        choices=[
                            ("SALE", "Sale"),
                            ("PURCHASE", "Purchase"),
                            ("ADJ", "Adjustment"),
                            ("TRANS_IN", "Transfer In"),
                            ("TRANS_OUT", "Transfer Out"),
                        ],
                        db_column="type",
                        db_index=True,
                        enum_type="stock_movement_type_enum",
                        help_text="Type of stock movement (PostgreSQL ENUM)",
                        max_length=20,
                    ),
                ),
                (
                    "quantity_delta",
                    models.DecimalField(
                        db_column="quantity_delta",
                        decimal_places=4,
                        help_text="Quantity moved (positive=in, negative=out)",
                        max_digits=16,
                    ),
                ),
                (
                    "cost_snapshot",
                    models.DecimalField(
                        blank=True,
                        db_column="cost_snapshot",
                        decimal_places=4,
                        help_text="Cost per unit at time of movement",
                        max_digits=16,
                        null=True,
                    ),
                ),
                (
                    "reference_id",
                    models.UUIDField(
                        blank=True,
                        db_index=True,
                        help_text="External reference (SaleID, PurchaseID, etc.)",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Movement notes", null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to="core.tenant",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Product being moved",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="inventario.product",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        help_text="Branch where movement occurred",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_movements",
                        to="core.branch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Movement",
                "verbose_name_plural": "Stock Movements",
                "db_table": "stock_movement",
                "ordering": ["-created_at"],
            },
        ),
        # 8. StockSnapshot (depends on: product, branch)
        migrations.CreateModel(
            name="StockSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="Current stock quantity",
                        max_digits=16,
                    ),
                ),
                (
                    "reserved_quantity",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        help_text="Reserved stock (pending orders)",
                        max_digits=16,
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, help_text="Timestamp of last update"),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        help_text="Branch",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_snapshots",
                        to="core.branch",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="Product",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_snapshots",
                        to="inventario.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stock Snapshot",
                "verbose_name_plural": "Stock Snapshots",
                "db_table": "stock_snapshot",
            },
        ),
        # Add constraints
        migrations.AddConstraint(
            model_name="productcategory",
            constraint=models.UniqueConstraint(
                fields=["tenant_id", "name"], name="unique_category_per_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="supplier",
            constraint=models.UniqueConstraint(
                fields=["tenant_id", "name"], name="unique_supplier_per_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="pricelist",
            constraint=models.UniqueConstraint(
                fields=["tenant_id", "name"], name="unique_pricelist_per_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=["tenant_id", "sku"], name="unique_sku_per_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="stocksnapshot",
            constraint=models.UniqueConstraint(
                fields=["branch_id", "product_id"], name="uq_stock_snapshot"
            ),
        ),
        # Add indexes
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["tenant_id", "category", "is_active"], name="idx_product_category"
            ),
        ),
        migrations.AddIndex(
            model_name="productpricehistory",
            index=models.Index(
                fields=["product_id", "price_list_id", "valid_from"],
                name="idx_price_history_validity",
            ),
        ),
        migrations.AddIndex(
            model_name="productcosthistory",
            index=models.Index(
                fields=["product_id", "valid_from"], name="idx_cost_history_validity"
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["tenant_id", "product_id", "created_at"], name="idx_movement_product_date"
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["tenant_id", "branch_id", "created_at"], name="idx_movement_branch_date"
            ),
        ),
    ]
