# Generated by Django 5.0.14 on 2025-12-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("inventario", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="attributes",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='\n        Custom product attributes (tenant-defined flexible schema).\n\n        Expected schema (flexible, tenant-specific):\n        {\n            "color": "string - product color",\n            "size": "string - product size (e.g., \'small\', \'medium\', \'large\')",\n            "weight": "float - product weight in kg",\n            "material": "string - primary material",\n            "brand": "string - brand name",\n            "dimensions": {\n                "length": "float - length in cm",\n                "width": "float - width in cm",\n                "height": "float - height in cm",\n                "unit": "string - measurement unit"\n            },\n            "certifications": ["list of certification codes"],\n            ... any other custom tenant-defined attributes\n        }\n\n        Note: Schema is completely flexible and tenant-defined. No validation\n        is enforced at the model level, allowing each tenant to customize\n        their product attribute structure based on their industry needs.\n        ',
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="ml_tags",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='\n        ML-generated categorization and predictive analytics metadata.\n\n        Expected schema for ML predictions:\n        {\n            "category_auto": "string - auto-detected product category",\n            "seasonality": "string - seasonal pattern (e.g., \'summer\', \'winter\',\n                           \'spring\', \'fall\', \'all_year\')",\n            "price_sensitivity": "string - price sensitivity level\n                                 (\'high\', \'medium\', \'low\')",\n            "demand_pattern": "string - demand pattern classification\n                              (\'steady\', \'volatile\', \'trending_up\', \'trending_down\',\n                              \'seasonal\', \'sporadic\')",\n            "reorder_prediction": "float - predicted days until reorder needed",\n            "predictions": {\n                "demand": {\n                    "next_7_days": "int - predicted demand for next week",\n                    "next_30_days": "int - predicted demand for next month",\n                    "confidence": "float - confidence score (0.0-1.0)"\n                },\n                "reorder": {\n                    "days_until_stockout": "int - predicted days until stockout",\n                    "recommended_quantity": "int - AI-recommended reorder quantity",\n                    "confidence": "float - confidence score (0.0-1.0)"\n                }\n            },\n            "seasonality_data": {\n                "pattern": "string - detected seasonal pattern",\n                "peak_months": ["list of int - peak demand months (1-12)"],\n                "multipliers": {\n                    "month_name": "float - seasonal demand multiplier"\n                }\n            },\n            "metadata": {\n                "last_updated": "string - ISO 8601 timestamp of last ML update",\n                "model_version": "string - ML model version used",\n                "accuracy_score": "float - model accuracy score (0.0-1.0)"\n            }\n        }\n\n        Note: This field is populated by ML services and should not be manually\n        edited in most cases. The schema may evolve as new ML models are deployed.\n        Empty dict {} is valid and indicates no ML analysis has been performed yet.\n        ',
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                condition=models.Q(("is_active", True)),
                fields=["tenant_id", "is_active"],
                name="idx_product_tenant_active",
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["tenant_id", "-created_at"], name="idx_movement_tenant_created"
            ),
        ),
        migrations.AddIndex(
            model_name="stocksnapshot",
            index=models.Index(
                fields=["branch_id", "product_id"], name="idx_stock_branch_product"
            ),
        ),
    ]
