# Generated by Django 5.2.11 on 2026-02-20 14:39

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_businesstemplate_tenantfielddefinition_and_more'),
        ('inventario', '0005_pricelist_unique_default_per_tenant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='attributes',
            new_name='custom_data',
        ),
        migrations.AddField(
            model_name='supplier',
            name='custom_data',
            field=models.JSONField(blank=True, default=dict, help_text='Tenant-defined custom fields. Validated against TenantFieldDefinition.'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['custom_data'], name='idx_product_custom_data', opclasses=['jsonb_path_ops']),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=django.contrib.postgres.indexes.GinIndex(fields=['custom_data'], name='idx_supplier_custom_data', opclasses=['jsonb_path_ops']),
        ),
    ]
