# Generated by Django 5.2.11 on 2026-02-24 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_product_supplier_to_compras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='custom_data',
            field=models.JSONField(blank=True, default=dict, help_text='Tenant-defined custom fields. Validated against TenantFieldDefinition.'),
        ),
    ]
