# Generated by Django 5.2.11 on 2026-02-24 20:47

import apps.core.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_businesstemplate_tenantfielddefinition_and_more'),
        ('gravitea_compras', '0001_initial'),
        ('inventario', '0009_purchase_order_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(help_text='Unique order number per tenant', max_length=32)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('CONFIRMED', 'Confirmado'), ('PARTIAL_RECEIVED', 'Parcialmente Recibida'), ('RECEIVED', 'Recibida'), ('CANCELLED', 'Cancelada')], db_index=True, default='DRAFT', max_length=20)),
                ('order_date', models.DateField(help_text='Date PO was created')),
                ('expected_delivery_date', models.DateField(blank=True, help_text='Optional estimated arrival', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('custom_data', models.JSONField(blank=True, default=dict, help_text='Tenant-defined custom fields. Validated against TenantFieldDefinition.')),
                ('total_amount', apps.core.fields.MoneyField(help_text='Sum of line_total values')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'db_table': 'compras_purchaseorder',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', apps.core.fields.MoneyField(help_text='Ordered quantity (> 0)')),
                ('unit_price', apps.core.fields.MoneyField(help_text='Price per unit (>= 0)')),
                ('line_total', apps.core.fields.MoneyField(help_text='Computed: quantity * unit_price')),
                ('received_quantity', apps.core.fields.MoneyField(help_text='Accumulated from GoodsReceiptLines')),
            ],
            options={
                'verbose_name': 'Purchase Order Item',
                'verbose_name_plural': 'Purchase Order Items',
                'db_table': 'compras_purchaseorderitem',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveIndex(
            model_name='supplier',
            name='idx_supplier_custom_data',
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=django.contrib.postgres.indexes.GinIndex(fields=['custom_data'], name='idx_supplier_custom_data', opclasses=['jsonb_path_ops']),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(help_text='Cannot delete supplier with open POs', on_delete=django.db.models.deletion.RESTRICT, related_name='purchase_orders', to='gravitea_compras.supplier'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='core.tenant'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='product',
            field=models.ForeignKey(help_text='Cannot delete product on open PO', on_delete=django.db.models.deletion.RESTRICT, related_name='purchase_order_items', to='inventario.product'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gravitea_compras.purchaseorder'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['tenant_id', 'status'], name='idx_po_tenant_status'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['tenant_id', 'supplier_id'], name='idx_po_tenant_supplier'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=django.contrib.postgres.indexes.GinIndex(fields=['custom_data'], name='idx_po_custom_data', opclasses=['jsonb_path_ops']),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'order_number'), name='unique_po_number_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='poi_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='poi_unit_price_non_negative'),
        ),
    ]
