# Generated by Django 5.2.11 on 2026-02-24 20:52

import apps.core.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_businesstemplate_tenantfielddefinition_and_more'),
        ('gravitea_compras', '0002_purchase_order_models'),
        ('inventario', '0009_purchase_order_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(help_text='Unique receipt number per tenant', max_length=32)),
                ('receipt_date', models.DateField(auto_now_add=True, help_text='Date goods arrived')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='goods_receipts', to='gravitea_compras.purchaseorder')),
                ('received_by', models.ForeignKey(blank=True, help_text='User who received the goods', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_receipts', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipts', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Goods Receipt',
                'verbose_name_plural': 'Goods Receipts',
                'db_table': 'compras_goodsreceipt',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_received', apps.core.fields.MoneyField(help_text='Quantity received (> 0)')),
                ('goods_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='gravitea_compras.goodsreceipt')),
                ('product', models.ForeignKey(help_text='Denormalized from PO item for easy access', on_delete=django.db.models.deletion.RESTRICT, related_name='goods_receipt_lines', to='inventario.product')),
                ('purchase_order_item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='receipt_lines', to='gravitea_compras.purchaseorderitem')),
            ],
            options={
                'verbose_name': 'Goods Receipt Line',
                'verbose_name_plural': 'Goods Receipt Lines',
                'db_table': 'compras_goodsreceiptline',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='goodsreceipt',
            index=models.Index(fields=['tenant_id', 'purchase_order_id'], name='idx_gr_tenant_po'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceipt',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'receipt_number'), name='unique_gr_number_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='goodsreceiptline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_received__gt', 0)), name='grl_quantity_positive'),
        ),
    ]
